# Generated by Django 5.1.4 on 2024-12-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category_post_cover_image_alter_post_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
