# Generated by Django 5.2 on 2025-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
