# Generated by Django 5.2 on 2025-08-13 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_options_alter_profile_options_profile_bio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the comment was last updated."
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, indicates when the post was published.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the comment is approved for public display.",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                help_text="Post that this comment belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                help_text="User who wrote the comment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                help_text="Author of the post.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional category for this post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image.",
                null=True,
                upload_to="covers/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Mark post as featured to pin on top."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                help_text="User account this profile belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
