# Generated by Django 5.2 on 2025-08-30 02:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment_updated_at_post_published_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image.",
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="covers/",
            ),
        ),
    ]
